# Generated by Django 2.1.4 on 2018-12-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vulner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=100)),
                ('vulner', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=5000)),
                ('published', models.CharField(max_length=50)),
            ],
        ),
    ]
