# Generated by Django 2.1.4 on 2018-12-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulners_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulner',
            name='vulner',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
