# Generated by Django 2.1.4 on 2018-12-16 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulners_engine', '0003_auto_20181216_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vulner',
            options={'ordering': ['-published']},
        ),
        migrations.AlterField(
            model_name='vulner',
            name='published',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
